changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: ✨ 新功能
      labels:
        - enhancement
        - feature
        - new
        - feat
    - title: 🐞 Bug 修复
      labels:
        - bug
        - fix
        - hotfix
    - title: ⚡ 性能优化
      labels:
        - performance
    - title: 📚 文档
      labels:
        - documentation
        - docs
    - title: 🧪 测试
      labels:
        - test
    - title: 🛠 构建/依赖
      labels:
        - build
        - dependencies
    - title: 其他变更
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog